server.port=8080
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka

# Disable processor CPU metrics to prevent NullPointerException with cgroup in Docker
management.metrics.enable.system.cpu=false
management.metrics.enable.process.cpu=false