spring.data.mongodb.uri=mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:root}@mongo:27017/product-service?authSource=admin
# Log a message when the "docker" profile is active
#logging.level.org.springframework.boot.autoconfigure=DEBUG
server.port=8080
eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka
management.metrics.enable.system.cpu=false
management.metrics.enable.process.cpu=false